name:                haskell
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

executables:
  scheme-exe:
    main:                Scheme.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
